# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://KraitGit.github.io/"

[social.params]
icon = "brand-github"


[[social]]
identifier = "CV"
name ="CV"
url = "https://KraitGit.github.io/CV_KIJUNG_JEON.pdf"

[[social.params]]
icon = "CV"